on:
  workflow_call:
    inputs:
      PARENT_BRANCH:
        description: "The master/main branch of the repository to compare files againt"
        type: string
        required: true
          
jobs:
  MyPy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: MyPy
        run: |
          export PARENT_BRANCH="${{ inputs.PARENT_BRANCH }}"
          source ./docker_env/make_docker.sh ""
          run_in_docker "./ci/run_mypy.sh"

      - name: Dump GitHub context
        if: ${{ always() }}
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
           JOB_CONTEXT: ${{ toJson(job) }}
           STEPS_CONTEXT: ${{ toJson(steps) }}
           RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "${GITHUB_CONTEXT}"
          echo "${JOB_CONTEXT}"
          echo "${STEPS_CONTEXT}"
          echo "${RUNNER_CONTEXT}"
          
